trigger:
- main

pool:
  name: 'default'
  demands:
    - Agent.Name -equals Muneer
variables:
  GCP_PROJECT_ID: 'your-gcp-project-id'
  IMAGE_NAME: 'nginx-app'
  IMAGE_TAG: '$(Build.BuildId)'
  GCR_PATH: 'gcr.io/your-gcp-project-id/nginx-app'
steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        gcloud auth activate-service-account --key-file=$(GCP_KEY_FILE)
        gcloud auth configure-docker
  
