trigger:
- main

pool:
  name: 'default'
  demands:
    - Agent.Name -equals Muneer
variables:
  GCP_PROJECT_ID: 'fabled-alchemy-449113-b9'
  IMAGE_NAME: 'nginx-app'
  IMAGE_TAG: '$(Build.BuildId)'
  GCR_HOSTNAME: 'gcr.io'
steps:
  - task: Docker@2
    displayName: "Build Docker Image"
    inputs:
      command: build
      dockerfile: 'Dockerfile'
      repository: "$(GCR_HOSTNAME)/$(GCP_PROJECT_ID)/$(IMAGE_NAME)"
      tags: "$(IMAGE_TAG)"
  - task: CmdLine@2
    inputs:
      script: |
        echo "Authenticating with GCP..."
        gcloud auth activate-service-account --key-file="C:\Users\v-muneshaik\agent\gcp\keyfile.json"
        gcloud auth configure-docker gcr.io
  - task: Docker@2
    displayName: "Push Docker Image to GCR"
    inputs:
      command: push
      repository: "gcr.io/fabled-alchemy-449113-b9/nginx-app"
      tags: "233"

  
